#!/bin/bash

xpm=$(cat);
title="$1"
: "${title:=xmp2html}"

nl=$'\n'
legend=$(echo "$xpm" | cut -d '"' -f 2 | grep ' c ')
last=$(echo "$legend" | tail -1)
lineno=$(echo "$xpm" | grep -n "$last" | cut -d : -f 1)
((lineno++));
pixels=$(echo "$xpm" | tail -n "+${lineno}" | cut -d '"' -f 2 | grep -v "^/\*" | grep -v "^};")
classes=
c=0
declare -A class_lookup
while read -r line
do
    sp_cnt=$(echo "$line" | grep -o ' ' | wc -l)
    if [ $sp_cnt -eq 1 ]; then
        key=" "
        val=$(echo "$line" | cut -d 'c' -f 2 | cut -d ' ' -f 2)
    else
        key=$(echo "$line" | cut -d ' ' -f 1)
        val=$(echo "$line" | cut -d ' ' -f 3)
    fi
    origval="$val"
    css=
    if [ "$val" = "None" ]; then
        css=""
    else
        css="background-color:${val}"
    fi
    classes="${classes}/*${key}|${val}*/ .c${c}{${css}}"
    class_lookup["$key"]="c${c}"
    ((c++));
done <<< "$legend"
legend=

echo "<!DOCTYPE html><html lang=\"en\"><HEAD><TITLE>${title}</TITLE><STYLE>"
html='
* { margin:0; padding:0; font-size:12px}
table, caption, tbody, tfoot, thead, tr, th, td {
    margin: 0;
    padding: 0;
    border: 0;
    outline: 0;
    border-collapse:collapse;
    /*font-size: 100%;*/
    /*vertical-align: baseline;*/
    /*background: transparent;*/
}
td {font-family: "Courier New";
border-spacing:0;
-webkit-border-horizontal-spacing: 0;
vertical-align: baseline;
font-size: 100%;
border-collapse: collapse;
}
td {
font-family: "Courier New";
font-size: 100%;
width:1px;
height:1px;
}'
echo "${html}"
echo "$classes"
echo "</STYLE></HEAD><body><table>"
row="<tr>"
tr=1
for ((i=0;i<${#pixels};i++));
do
    if [ $tr -eq 0 ]; then
        row="<tr>"
        tr=1
    fi
    if [ "${pixels:$i:1}" = "$nl" ]; then
        echo "$row</tr>"
        tr=0
    else
        p="${pixels:$i:1}"
        class=${class_lookup["$p"]}
        row="${row}<td class='$class'></td>"
    fi
done
if [ $tr -eq 1 ]; then
    echo "$row</tr>"
fi
echo "</table></body></html>"
