#!/bin/bash

xpm=$(cat);

nl=$'\n'
legend=$(echo "$xpm" | cut -d '"' -f 2 | grep ' c ')
last=$(echo "$legend" | tail -1)
lineno=$(echo "$xpm" | grep -n "$last" | cut -d : -f 1)
((lineno++));
pixels=$(echo "$xpm" | tail -n "+${lineno}" | cut -d '"' -f 2 | grep -v "^/\*" | grep -v "^};")

#echo "$pixels"
html='<html><HEAD><STYLE>

/* table, */
/* thead, */
/* tbody, */
/* tfoot, */
/* tr, */
/* th, */
/* td { */
/*     /\*display: block;*\/ */
/*     width: 1px; */
/*     height: 1px; */
/*     margin: 0; */
/*     padding: 0; */
/*     /\*border: none;*\/ */
/*     /\*border-collapse: inherit;*\/ */
/*     /\*border-spacing: 0;*\/ */
/*     /\*border-color: inherit; */
/*     vertical-align: inherit; */
/*     text-align: left; */
/*     font-weight: inherit;*\/ */
/*     /\*-webkit-border-horizontal-spacing: 0; */
/*     -webkit-border-vertical-spacing: 0;*\/ */
/*  }th, td { */
/*     /\*display: inline;*\/ */
/* } */
* { margin:0; padding:0; font-size:12px}
table, caption, tbody, tfoot, thead, tr, th, td {
    margin: 0;
    padding: 0;
    border: 0;
    outline: 0;
    border-collapse:collapse;
    /*font-size: 100%;*/
    /*vertical-align: baseline;*/
    /*background: transparent;*/
}
td {font-family: "Courier New";
border-spacing:0;
-webkit-border-horizontal-spacing: 0;
vertical-align: baseline;
font-size: 100%;
border-collapse: collapse;
}
td {
font-family: "Courier New";
font-size: 100%;
width:1px;
height:1px;

}


</STYLE></HEAD><body><table><tr>'
tr=1
cachekey=""
cacheval=""
tdl="<td style='background-color:"
tdr="'> </td>"
for ((i=0;i<${#pixels};i++));
do
    if [ $tr -eq 0 ]; then
        html="${html}<tr>"
        tr=1
    fi
    if [ "${pixels:$i:1}" = "$nl" ]; then
        html="${html}</tr>";
        echo "<!-- line -->"
        tr=0
    else
        p="${pixels:$i:1}"
        #if [ "$cachekey" = "$p" ]; then
        #    color="$cacheval"
        #else
            for ((j=0;j<${#legend};j++));
            do
                #echo "$j"
                if [ "${p}" = "${legend:$j:1}" ]; then
                    ((j=j+4)); color=""
                    while [[ ! "${legend:$j:1}" = "$nl" && $j -lt ${#legend}  ]]
                    do
                        color="$color${legend:$j:1}"
                        ((j=j+1))
                        #echo "${legend:$j:1}"
                    done
                    break
                else
                    while [[ ! "${legend:$j:1}" = "$nl"  && $j -lt ${#legend} ]]
                    do
                        ((j=j+1))
                        #echo "${legend:$j:1}"
                    done
                fi
            done
        #fi
        #cacheval="$color"
        #cachekey="${pixels:$i:1}"
        if [ "$color" = "None" ]; then
            html="${html}<td></td>"
        else
            html="${html}${tdl}${color}${tdr}"
        fi
    fi
done
html="${html}</table></body></html>"
echo "$html"
